### ISSUE TITLE
About the gameplay issue while interpreting

### ISSUE THREAD

**Issue by LinJiaShen** [timcsy/GameAIKart#10]
Hi Tim,

Some issues happened when I executed the command with "python ml.py",
the game seems not to be functioning on the display window

I've wondered if I am installing it incorrectly or what, and how do I fix this problem?

Thanks,
Jashen

**Comment by timcsy** [comment]
Hello @LinJiaShen,

Thanks for raising your issue, maybe you can try to edit the "PAIA_ID" in the .env configuration file to 50051 (or some integer between 10000 to 65535) and run the "python ml.py" script again.

Sincerely,
timcsy
