### ISSUE TITLE
Episode does not terminate when race ends

### ISSUE THREAD

**Issue by chocola-mint** [timcsy/GameAIKart#7]
Currently, an episode does not terminate when the agent completes a race. The training process is just stuck in the result screen. (e.g. terminal_steps is always empty)

There isn't any observable signals that could determine that the agent has finished a lap, either, so the agent can't stop on its own.

We would appreciate it if this issue could be addressed soon, so that our agents can actually optimize finishing time rather than just learning how to drive safely (ending an episode when it gets too close to a wall, etc.)

**Comment by timcsy** [comment]
Hello, currently you can call EndEpisode() of an PAIAKartAgent object or set the Max Step in the Unity manually to terminate an episode.
And we are shifting to a new interface to provide a more clearly and more conveniently spec, which will be update soon.

**Comment by timcsy** [comment]
The API has update now, check this page: https://github.com/timcsy/GameAIKart/tree/main/PAIA for more information.

We have add some events like win, timeout, undrivable, finish at the terminate state.
